// All user-facing copy, keyed by language code.
// "ta" = Tamil, "hi" = Hindi, "en" = English.
//
// The opening screen is shown BEFORE a language is chosen, so it must
// stay understandable to someone who only reads one of the three
// scripts. WELCOME_TRIO holds that shared, always-trilingual content;
// COPY holds the per-language strings used everywhere else, once a
// language has been picked.

// Brand name is kept in Latin script across all three languages —
// consistent with how most Indian government portals keep an English
// program name as the fixed identity mark, translating everything
// around it.
export const BRAND_NAME = 'LangDoc AI'

export const WELCOME_TRIO = [
  {
    code: 'en',
    scriptClass: '',
    label: 'English',
    tagline: 'Your Document Assistant',
    desc: 'Photograph your document and we will explain it in simple English, and read it aloud.',
    start: 'Continue in English',
  },
  
  {
    code: 'hi',
    scriptClass: 'lang-hi',
    label: 'हिन्दी',
    tagline: 'आपका दस्तावेज़ सहायक',
    desc: 'दस्तावेज़ की तस्वीर लें, हम इसे आसान हिन्दी में समझाकर पढ़कर भी सुनाएँगे।',
    start: 'हिन्दी में जारी रखें',
  },
  {
    code: 'ta',
    scriptClass: 'lang-ta',
    label: 'தமிழ்',
    tagline: 'உங்கள் ஆவண உதவியாளர்',
    desc: 'ஆவணத்தின் புகைப்படம் எடுங்கள், நாங்கள் அதை எளிய தமிழில் விளக்கி, படித்துக் காட்டுகிறோம்.',
    start: 'தமிழில் தொடரவும்',
  },
]

export const WELCOME_PURPOSE = {
  en: 'An initiative to help senior citizens and every citizen understand government, bank, and hospital documents in their own language.',
  hi: 'सरकारी, बैंक और अस्पताल के दस्तावेज़ समझने में कठिनाई महसूस करने वाले वरिष्ठ नागरिकों और सभी के लिए एक पहल।',
  ta: 'அரசு, வங்கி, மருத்துவமனை ஆவணங்களைப் புரிந்துகொள்ள சிரமப்படும் மூத்த குடிமக்கள் மற்றும் அனைவருக்கும் உதவும் ஒரு முயற்சி.',
}

export const COPY = {
  en: {
    appTitle: BRAND_NAME,
    tagline: 'Your Document Assistant',
    startButton: 'Get started',
    chooseLanguage: 'Choose your language',
    languageHelp: 'The explanation will be shown and read aloud in this language',
    tamil: 'தமிழ்',
    hindi: 'हिन्दी',
    english: 'English',
    continue: 'Continue',
    back: 'Back',
    uploadTitle: 'Show us your document',
    uploadHelp: 'Take a photo or choose one from your gallery',
    takePhoto: 'Take a photo',
    uploadImage: 'Upload a photo',
    changeImage: 'Change photo',
    explainButton: 'Explain my document',
    loadingSteps: [
      'Understanding your document...',
      'Finding the important details...',
      'Simplifying the language...',
      'Preparing the voice explanation...',
    ],
    resultTitle: 'Your document explained',
    documentType: 'Document type',
    summary: 'Simple explanation',
    actionRequired: 'What you need to do',
    deadline: 'Deadline',
    priority: 'Priority',
    urgencyReason: 'Why it matters',
    estimatedTime: 'Time needed',
    documentsRequired: 'Documents required',
    keyPoints: 'Key points',
    englishGloss: 'English verification',
    listenLabel: 'Listen to the explanation',
    playAgain: 'Play again',
    newDocument: 'New document',
    trustLine: 'Your information stays safe',
    lightMode: 'Light mode',
    darkMode: 'Dark mode',
    changeLanguage: 'Change language',
    qaTitle: 'Do you want to ask something?',
    qaHelp: 'Press the mic button and speak your question',
    qaMicIdle: 'Ask a question',
    qaListening: 'Listening...',
    qaThinking: 'Getting your answer...',
    qaAnswerLabel: 'Answer',
    qaYourQuestion: 'Your question',
    qaTextPlaceholder: 'Type your question here',
    qaTextSend: 'Send',
    qaUnsupported: 'Voice input is not available on this device. Please type your question instead.',
    qaMicError: 'Microphone access was not granted. Please type your question instead.',
    qaListenAnswer: 'Listen to the answer',
    qaPlayAgain: 'Play again',
    guideTitle: 'Form Guidance',
    guideHelp: 'Get step-by-step help filling this form',
    guideStart: 'Start Guide',
    guideLoading: 'Starting...',
    guideNext: 'Next Step',
    guideListen: 'Listen to instructions',
    guidePlayAgain: 'Play Again',
    guideCompleted: 'Guide Completed!',
    guideCompletedMessage: 'You have completed all the steps.',
  },
  hi: {
    appTitle: BRAND_NAME,
    tagline: 'आपका दस्तावेज़ सहायक',
    startButton: 'शुरू करें',
    chooseLanguage: 'अपनी भाषा चुनें',
    languageHelp: 'व्याख्या इसी भाषा में पढ़ी और सुनाई जाएगी',
    tamil: 'தமிழ்',
    hindi: 'हिन्दी',
    english: 'English',
    continue: 'आगे बढ़ें',
    back: 'वापस जाएँ',
    uploadTitle: 'अपना दस्तावेज़ दिखाएँ',
    uploadHelp: 'तस्वीर लें या फोटो चुनें',
    takePhoto: 'तस्वीर लें',
    uploadImage: 'फोटो अपलोड करें',
    changeImage: 'फोटो बदलें',
    explainButton: 'मेरा दस्तावेज़ समझाएँ',
    loadingSteps: [
      'आपका दस्तावेज़ समझ रहे हैं...',
      'ज़रूरी जानकारी ढूंढ रहे हैं...',
      'भाषा को आसान बना रहे हैं...',
      'आवाज़ में व्याख्या तैयार कर रहे हैं...',
    ],
    resultTitle: 'आपके दस्तावेज़ की व्याख्या',
    documentType: 'दस्तावेज़ का प्रकार',
    summary: 'आसान व्याख्या',
    actionRequired: 'आपको क्या करना है',
    deadline: 'अंतिम तिथि',
    priority: 'प्राथमिकता',
    urgencyReason: 'यह ज़रूरी क्यों है',
    estimatedTime: 'लगने वाला समय',
    documentsRequired: 'ज़रूरी दस्तावेज़',
    keyPoints: 'मुख्य बिंदु',
    englishGloss: 'अंग्रेज़ी पुष्टि',
    listenLabel: 'व्याख्या सुनें',
    playAgain: 'फिर से सुनें',
    newDocument: 'नया दस्तावेज़',
    trustLine: 'आपकी जानकारी सुरक्षित है',
    lightMode: 'लाइट मोड',
    darkMode: 'डार्क मोड',
    changeLanguage: 'भाषा बदलें',
    qaTitle: 'क्या आप कुछ पूछना चाहते हैं?',
    qaHelp: 'माइक बटन दबाएँ और अपना सवाल बोलें',
    qaMicIdle: 'सवाल पूछें',
    qaListening: 'सुन रहे हैं...',
    qaThinking: 'जवाब तैयार हो रहा है...',
    qaAnswerLabel: 'जवाब',
    qaYourQuestion: 'आपका सवाल',
    qaTextPlaceholder: 'अपना सवाल यहाँ टाइप करें',
    qaTextSend: 'भेजें',
    qaUnsupported: 'इस डिवाइस पर आवाज़ से सवाल पूछना उपलब्ध नहीं है। कृपया टाइप करके पूछें।',
    qaMicError: 'माइक की अनुमति नहीं मिली। कृपया टाइप करके पूछें।',
    qaListenAnswer: 'जवाब सुनें',
    qaPlayAgain: 'फिर से सुनें',
    guideTitle: 'फ़ॉर्म मार्गदर्शन',
    guideHelp: 'इस फ़ॉर्म को भरने में चरण-दर-चरण मदद पाएं',
    guideStart: 'गाइड शुरू करें',
    guideLoading: 'शुरू हो रहा है...',
    guideNext: 'अगला चरण',
    guideListen: 'निर्देश सुनें',
    guidePlayAgain: 'फिर से सुनें',
    guideCompleted: 'गाइड पूरा हो गया!',
    guideCompletedMessage: 'आपने सभी चरण पूरे कर लिए हैं।',
  },
  
  ta: {
    appTitle: BRAND_NAME,
    tagline: 'உங்கள் ஆவண உதவியாளர்',
    startButton: 'தொடங்குங்கள்',
    chooseLanguage: 'உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்',
    languageHelp: 'விளக்கம் இந்த மொழியில் கேட்கவும், படிக்கவும் கிடைக்கும்',
    tamil: 'தமிழ்',
    hindi: 'हिन्दी',
    english: 'English',
    continue: 'தொடரவும்',
    back: 'பின்செல்',
    uploadTitle: 'உங்கள் ஆவணத்தைக் காட்டுங்கள்',
    uploadHelp: 'புகைப்படம் எடுக்கவும் அல்லது படத்தைத் தேர்ந்தெடுக்கவும்',
    takePhoto: 'புகைப்படம் எடுக்கவும்',
    uploadImage: 'படத்தைப் பதிவேற்றவும்',
    changeImage: 'படத்தை மாற்றவும்',
    explainButton: 'என் ஆவணத்தை விளக்குங்கள்',
    loadingSteps: [
      'உங்கள் ஆவணத்தைப் புரிந்துகொள்கிறோம்...',
      'முக்கியமான விவரங்களைக் கண்டறிகிறோம்...',
      'மொழியை எளிமையாக்குகிறோம்...',
      'குரல் விளக்கத்தைத் தயார் செய்கிறோம்...',
    ],
    resultTitle: 'உங்கள் ஆவண விளக்கம்',
    documentType: 'ஆவண வகை',
    summary: 'எளிய விளக்கம்',
    actionRequired: 'நீங்கள் செய்ய வேண்டியது',
    deadline: 'கடைசி தேதி',
    priority: 'முக்கியத்துவம்',
    urgencyReason: 'ஏன் அவசரம்',
    estimatedTime: 'தேவைப்படும் நேரம்',
    documentsRequired: 'தேவையான ஆவணங்கள்',
    keyPoints: 'முக்கிய குறிப்புகள்',
    englishGloss: 'ஆங்கில சரிபார்ப்பு',
    listenLabel: 'விளக்கத்தைக் கேளுங்கள்',
    playAgain: 'மீண்டும் கேளுங்கள்',
    newDocument: 'புதிய ஆவணம்',
    trustLine: 'உங்கள் தகவல் பாதுகாப்பாக உள்ளது',
    lightMode: 'வெளிர் பயன்முறை',
    darkMode: 'இருள் பயன்முறை',
    changeLanguage: 'மொழியை மாற்றவும்',
    qaTitle: 'ஏதேனும் கேட்க விரும்புகிறீர்களா?',
    qaHelp: 'மைக் பொத்தானை அழுத்தி உங்கள் கேள்வியைப் பேசுங்கள்',
    qaMicIdle: 'கேள்வி கேளுங்கள்',
    qaListening: 'கேட்டுக்கொண்டிருக்கிறோம்...',
    qaThinking: 'பதில் தயாராகிறது...',
    qaAnswerLabel: 'பதில்',
    qaYourQuestion: 'உங்கள் கேள்வி',
    qaTextPlaceholder: 'உங்கள் கேள்வியை இங்கே தட்டச்சு செய்யவும்',
    qaTextSend: 'அனுப்பவும்',
    qaUnsupported: 'இந்த சாதனத்தில் குரல் உள்ளீடு கிடைக்கவில்லை. தட்டச்சு செய்து கேளுங்கள்.',
    qaMicError: 'மைக்குக்கு அனுமதி கிடைக்கவில்லை. தட்டச்சு செய்து கேளுங்கள்.',
    qaListenAnswer: 'பதிலைக் கேளுங்கள்',
    qaPlayAgain: 'மீண்டும் கேளுங்கள்',
    guideTitle: 'படிவ வழிகாட்டுதல்',
    guideHelp: 'இந்த படிவத்தை நிரப்ப சரம்-சரமாக உதவுங்கள்',
    guideStart: 'வழிகாட்டுதலைத் தொடங்கு',
    guideLoading: 'தொடங்குகிறது...',
    guideNext: 'அடுத்த படி',
    guideListen: 'வழிமுறைகளைக் கேளுங்கள்',
    guidePlayAgain: 'மீண்டும் கேளுங்கள்',
    guideCompleted: 'வழிகாட்டுதல் முடிந்தது!',
    guideCompletedMessage: 'நீங்கள் அனைத்து படிகளையும் முடித்துவிட்டீர்கள்.',
  },
}
